/**
 * ratings.js — the ratings seed, as a plain ES module.
 *
 * This used to be ratings.json loaded through node:module createRequire. That
 * works in Node and nowhere else: a Vercel serverless bundle and a browser
 * bundle both have to resolve it too, and JSON import attributes are not
 * supported consistently across the bundlers involved. Exporting the same data
 * from a .js module needs no import attributes, no loader hooks and no build
 * step, and it behaves identically in all three environments.
 *
 * Content is byte-for-byte the old JSON seed (verified by round-tripping
 * JSON.stringify before the .json file was deleted, so there is one source of
 * truth rather than two that can drift). Numbers are a starting prior — the
 * engine blends them with live market consensus at 8% weight, so a stale rating
 * degrades gracefully instead of breaking the model.
 */

export const RATINGS = {
  "_about": "RolloverEngine ratings seed. Football: att = attacking strength, def = defensive vulnerability (1.0 = league average, higher def = leakier). Basketball/baseball: rtg = points/runs per game better than league average. Tennis/MMA: rtg = 0-100 skill index. These are a starting prior — the engine blends them with live market consensus, so a stale rating degrades gracefully instead of breaking the model.",
  "football": [
    {
      "code": "EPL",
      "name": "Premier League",
      "country": "England",
      "base": 1.42,
      "tier": 1,
      "noise": 0.05,
      "teams": [
        ["Manchester City", "MCI", 1.62, 0.74],
        ["Arsenal", "ARS", 1.5, 0.7],
        ["Liverpool", "LIV", 1.58, 0.82],
        ["Chelsea", "CHE", 1.34, 0.92],
        ["Tottenham", "TOT", 1.38, 1.02],
        ["Manchester United", "MUN", 1.16, 1.02],
        ["Newcastle", "NEW", 1.34, 0.9],
        ["Aston Villa", "AVL", 1.34, 1.02],
        ["Brighton", "BHA", 1.24, 1],
        ["West Ham", "WHU", 1.02, 1.08],
        ["Crystal Palace", "CRY", 1.08, 0.94],
        ["Brentford", "BRE", 1.2, 1.12],
        ["Fulham", "FUL", 1.08, 0.98],
        ["Bournemouth", "BOU", 1.22, 1.04],
        ["Wolves", "WOL", 0.94, 1.1],
        ["Everton", "EVE", 0.88, 0.96],
        ["Nottingham Forest", "NFO", 1.02, 0.9],
        ["Leeds", "LEE", 0.98, 1.14],
        ["Burnley", "BUR", 0.82, 1.16],
        ["Sunderland", "SUN", 0.9, 1.06],
      ],
    },
    {
      "code": "LALIGA",
      "name": "La Liga",
      "country": "Spain",
      "base": 1.3,
      "tier": 1,
      "noise": 0.05,
      "teams": [
        ["Real Madrid", "RMA", 1.66, 0.76],
        ["Barcelona", "BAR", 1.72, 0.92],
        ["Atlético Madrid", "ATM", 1.28, 0.74],
        ["Athletic Club", "ATH", 1.18, 0.84],
        ["Real Sociedad", "RSO", 1.02, 0.92],
        ["Villarreal", "VIL", 1.24, 1.04],
        ["Real Betis", "BET", 1.1, 0.98],
        ["Sevilla", "SEV", 0.94, 1.02],
        ["Valencia", "VAL", 0.94, 1.06],
        ["Girona", "GIR", 1.06, 1.1],
        ["Osasuna", "OSA", 0.92, 1],
        ["Celta Vigo", "CEL", 1.06, 1.12],
        ["Rayo Vallecano", "RAY", 0.92, 0.96],
        ["Getafe", "GET", 0.8, 0.92],
        ["Mallorca", "MLL", 0.82, 0.96],
        ["Alavés", "ALA", 0.86, 1.04],
        ["Espanyol", "ESP", 0.86, 1.08],
        ["Levante", "LEV", 0.88, 1.14],
        ["Elche", "ELC", 0.84, 1.06],
        ["Real Oviedo", "OVI", 0.76, 1.08],
      ],
    },
    {
      "code": "SERIEA",
      "name": "Serie A",
      "country": "Italy",
      "base": 1.34,
      "tier": 1,
      "noise": 0.05,
      "teams": [
        ["Inter", "INT", 1.56, 0.76],
        ["Juventus", "JUV", 1.22, 0.78],
        ["AC Milan", "MIL", 1.38, 0.98],
        ["Napoli", "NAP", 1.32, 0.82],
        ["Atalanta", "ATA", 1.5, 1.02],
        ["Roma", "ROM", 1.22, 0.9],
        ["Lazio", "LAZ", 1.18, 0.98],
        ["Fiorentina", "FIO", 1.16, 1.02],
        ["Bologna", "BOL", 1.1, 0.92],
        ["Torino", "TOR", 0.92, 0.98],
        ["Udinese", "UDI", 0.94, 1.04],
        ["Genoa", "GEN", 0.86, 1.02],
        ["Como", "COM", 1.02, 1],
        ["Cagliari", "CAG", 0.88, 1.1],
        ["Lecce", "LEC", 0.76, 1.06],
        ["Parma", "PAR", 0.86, 1.08],
        ["Hellas Verona", "VER", 0.84, 1.16],
        ["Sassuolo", "SAS", 0.92, 1.14],
        ["Cremonese", "CRE", 0.8, 1.08],
        ["Pisa", "PIS", 0.74, 1.06],
      ],
    },
    {
      "code": "BUNDES",
      "name": "Bundesliga",
      "country": "Germany",
      "base": 1.58,
      "tier": 1,
      "noise": 0.05,
      "teams": [
        ["Bayern München", "BAY", 1.86, 0.8],
        ["Leverkusen", "LEV", 1.52, 0.92],
        ["Dortmund", "BVB", 1.5, 1.02],
        ["RB Leipzig", "RBL", 1.34, 0.96],
        ["Eintracht Frankfurt", "SGE", 1.34, 1.1],
        ["Stuttgart", "VFB", 1.3, 1.08],
        ["Freiburg", "SCF", 1.06, 1],
        ["Hoffenheim", "TSG", 1.16, 1.18],
        ["Wolfsburg", "WOB", 1.08, 1.12],
        ["Mönchengladbach", "BMG", 1.04, 1.16],
        ["Mainz", "M05", 1, 0.98],
        ["Werder Bremen", "SVW", 1.1, 1.24],
        ["Augsburg", "FCA", 0.92, 1.14],
        ["Union Berlin", "FCU", 0.84, 1.02],
        ["St. Pauli", "STP", 0.8, 1.06],
        ["Köln", "KOE", 0.94, 1.2],
        ["Heidenheim", "FCH", 0.9, 1.22],
        ["Hamburg", "HSV", 0.96, 1.18],
      ],
    },
    {
      "code": "LIGUE1",
      "name": "Ligue 1",
      "country": "France",
      "base": 1.38,
      "tier": 1,
      "noise": 0.05,
      "teams": [
        ["Paris SG", "PSG", 1.78, 0.76],
        ["Monaco", "MON", 1.34, 1],
        ["Marseille", "OM", 1.38, 1],
        ["Lille", "LIL", 1.16, 0.9],
        ["Lyon", "LYO", 1.3, 1.06],
        ["Nice", "NIC", 1.06, 0.9],
        ["Lens", "RCL", 1.1, 0.94],
        ["Rennes", "REN", 1.1, 1.06],
        ["Strasbourg", "STR", 1.06, 1.06],
        ["Toulouse", "TFC", 0.98, 1],
        ["Nantes", "NAN", 0.86, 1.08],
        ["Brest", "BRE", 1.02, 1.12],
        ["Le Havre", "HAC", 0.84, 1.12],
        ["Angers", "ANG", 0.82, 1.1],
        ["Auxerre", "AJA", 0.9, 1.14],
        ["Metz", "MET", 0.78, 1.18],
        ["Lorient", "FCL", 0.88, 1.16],
        ["Paris FC", "PFC", 0.9, 1.1],
      ],
    },
    {
      "code": "ERE",
      "name": "Eredivisie",
      "country": "Netherlands",
      "base": 1.66,
      "tier": 2,
      "noise": 0.07,
      "teams": [
        ["Ajax", "AJA", 1.6, 0.9],
        ["PSV", "PSV", 1.86, 0.8],
        ["Feyenoord", "FEY", 1.52, 0.92],
        ["AZ Alkmaar", "AZ", 1.34, 1],
        ["Twente", "TWE", 1.24, 1],
        ["Utrecht", "UTR", 1.2, 1.04],
        ["Go Ahead Eagles", "GAE", 1.02, 1.06],
        ["NEC", "NEC", 1.06, 1.1],
        ["Heerenveen", "HEE", 1, 1.14],
        ["Sparta Rotterdam", "SPA", 0.94, 1.1],
        ["Groningen", "GRO", 0.92, 1.12],
        ["Fortuna Sittard", "FOR", 0.86, 1.14],
        ["PEC Zwolle", "PEC", 0.88, 1.18],
        ["Volendam", "VOL", 0.9, 1.28],
        ["Excelsior", "EXC", 0.84, 1.24],
        ["NAC Breda", "NAC", 0.82, 1.2],
        ["Telstar", "TEL", 0.76, 1.18],
        ["Heracles", "HER", 0.84, 1.26],
      ],
    },
    {
      "code": "LIGAP",
      "name": "Liga Portugal",
      "country": "Portugal",
      "base": 1.36,
      "tier": 2,
      "noise": 0.07,
      "teams": [
        ["Benfica", "BEN", 1.62, 0.8],
        ["Porto", "POR", 1.56, 0.78],
        ["Sporting CP", "SCP", 1.72, 0.76],
        ["Braga", "BRA", 1.3, 0.96],
        ["Vitória SC", "VSC", 1.08, 1],
        ["Moreirense", "MOR", 0.92, 1],
        ["Famalicão", "FAM", 0.98, 0.98],
        ["Gil Vicente", "GIL", 0.9, 1.04],
        ["Estoril", "EST", 0.92, 1.1],
        ["Arouca", "ARO", 0.88, 1.14],
        ["Casa Pia", "CAS", 0.82, 1.06],
        ["Rio Ave", "RIO", 0.84, 1.1],
        ["Santa Clara", "STA", 0.86, 1.04],
        ["Nacional", "NAC", 0.8, 1.12],
        ["AVS", "AVS", 0.74, 1.16],
        ["Estrela Amadora", "AMA", 0.78, 1.14],
        ["Alverca", "ALV", 0.76, 1.12],
        ["Tondela", "TON", 0.72, 1.14],
      ],
    },
    {
      "code": "SPFL",
      "name": "Scottish Premiership",
      "country": "Scotland",
      "base": 1.48,
      "tier": 2,
      "noise": 0.08,
      "teams": [
        ["Celtic", "CEL", 1.9, 0.72],
        ["Rangers", "RAN", 1.66, 0.8],
        ["Hearts", "HEA", 1.16, 0.94],
        ["Hibernian", "HIB", 1.06, 1.02],
        ["Aberdeen", "ABE", 1.02, 1.06],
        ["Dundee United", "DUN", 0.94, 1.06],
        ["Motherwell", "MOT", 0.92, 1.08],
        ["Kilmarnock", "KIL", 0.9, 1.04],
        ["St Mirren", "STM", 0.82, 1.08],
        ["Dundee", "DDD", 0.84, 1.16],
        ["Falkirk", "FAL", 0.8, 1.14],
        ["Livingston", "LIV", 0.76, 1.12],
      ],
    },
    {
      "code": "SULIG",
      "name": "Süper Lig",
      "country": "Türkiye",
      "base": 1.46,
      "tier": 2,
      "noise": 0.09,
      "teams": [
        ["Galatasaray", "GAL", 1.72, 0.82],
        ["Fenerbahçe", "FEN", 1.66, 0.84],
        ["Beşiktaş", "BES", 1.34, 0.98],
        ["Trabzonspor", "TRA", 1.26, 1],
        ["Samsunspor", "SAM", 1.1, 0.98],
        ["Başakşehir", "BAS", 1.08, 1.02],
        ["Göztepe", "GOZ", 1, 0.96],
        ["Konyaspor", "KON", 0.96, 1.06],
        ["Rizespor", "RIZ", 0.94, 1.12],
        ["Antalyaspor", "ANT", 0.92, 1.1],
        ["Alanyaspor", "ALA", 0.94, 1.08],
        ["Kasımpaşa", "KAS", 0.9, 1.16],
        ["Gaziantep FK", "GAZ", 0.88, 1.12],
        ["Kayserispor", "KAY", 0.86, 1.18],
        ["Eyüpspor", "EYU", 0.88, 1.14],
        ["Kocaelispor", "KOC", 0.82, 1.14],
        ["Gençlerbirliği", "GEN", 0.8, 1.16],
        ["Karagümrük", "KAR", 0.84, 1.2],
      ],
    },
    {
      "code": "BRSA",
      "name": "Brasileirão Série A",
      "country": "Brazil",
      "base": 1.16,
      "tier": 2,
      "noise": 0.07,
      "teams": [
        ["Flamengo", "FLA", 1.56, 0.78],
        ["Palmeiras", "PAL", 1.42, 0.74],
        ["Botafogo", "BOT", 1.28, 0.88],
        ["São Paulo", "SAO", 1.1, 0.9],
        ["Corinthians", "COR", 1.06, 0.96],
        ["Cruzeiro", "CRU", 1.22, 0.86],
        ["Atlético Mineiro", "CAM", 1.2, 1],
        ["Fluminense", "FLU", 1.08, 0.94],
        ["Grêmio", "GRE", 1, 1.02],
        ["Internacional", "INT", 1.06, 0.98],
        ["Bahia", "BAH", 1.14, 0.96],
        ["Fortaleza", "FOR", 1.04, 1],
        ["Vasco da Gama", "VAS", 0.96, 1.04],
        ["Bragantino", "BRA", 1.02, 1.06],
        ["Santos", "SAN", 0.98, 1.06],
        ["Ceará", "CEA", 0.86, 1.02],
        ["Vitória", "VIT", 0.84, 1.06],
        ["Mirassol", "MIR", 0.94, 0.98],
        ["Juventude", "JUV", 0.86, 1.12],
        ["Sport Recife", "SPO", 0.78, 1.08],
      ],
    },
    {
      "code": "ARGP",
      "name": "Liga Profesional",
      "country": "Argentina",
      "base": 1.12,
      "tier": 2,
      "noise": 0.08,
      "teams": [
        ["Boca Juniors", "BOC", 1.24, 0.94],
        ["River Plate", "RIV", 1.36, 0.88],
        ["Racing Club", "RAC", 1.2, 0.98],
        ["Independiente", "IND", 1.02, 1],
        ["San Lorenzo", "SLO", 0.94, 0.96],
        ["Vélez Sarsfield", "VEL", 1.14, 0.92],
        ["Estudiantes", "EST", 1.1, 0.94],
        ["Argentinos Juniors", "AAJ", 1.02, 0.98],
        ["Talleres", "TAL", 1.08, 1],
        ["Rosario Central", "ROS", 1.06, 0.96],
        ["Newell's Old Boys", "NOB", 0.92, 1],
        ["Lanús", "LAN", 1.04, 0.98],
        ["Huracán", "HUR", 0.94, 0.94],
        ["Belgrano", "BEL", 0.92, 1.02],
        ["Banfield", "BAN", 0.88, 1.02],
        ["Tigre", "TIG", 0.88, 1.04],
        ["Unión", "UNI", 0.86, 1],
        ["Defensa y Justicia", "DYJ", 0.96, 1.06],
        ["Central Córdoba", "CCA", 0.84, 1.04],
        ["Instituto", "INS", 0.86, 1.06],
      ],
    },
    {
      "code": "NPFL",
      "name": "Nigeria Premier League",
      "country": "Nigeria",
      "base": 1.1,
      "tier": 3,
      "noise": 0.12,
      "teams": [
        ["Enyimba", "ENY", 1.38, 0.86],
        ["Rivers United", "RIV", 1.34, 0.84],
        ["Remo Stars", "REM", 1.3, 0.86],
        ["Rangers Intl", "RAN", 1.2, 0.9],
        ["Plateau United", "PLA", 1.14, 0.94],
        ["Enugu Rangers", "ENG", 1.1, 0.96],
        ["Kano Pillars", "KAN", 1.12, 1],
        ["Shooting Stars", "SHO", 1.06, 0.98],
        ["Bendel Insurance", "BEN", 1.02, 0.98],
        ["Nasarawa United", "NAS", 0.96, 1.02],
        ["El-Kanemi Warriors", "ELK", 0.92, 1.04],
        ["Ihefu FC", "IHE", 0.9, 1.04],
        ["Wikki Tourists", "WIK", 0.94, 1.06],
        ["Kwara United", "KWA", 0.98, 1.02],
        ["Abia Warriors", "ABI", 0.88, 1.06],
        ["Heartland", "HEA", 0.92, 1.08],
        ["Gombe United", "GOM", 0.86, 1.08],
        ["Katsina United", "KAT", 0.84, 1.06],
        ["Sunshine Stars", "SUN", 0.88, 1.1],
        ["Bayelsa United", "BAY", 0.86, 1.08],
      ],
    },
    {
      "code": "SPL",
      "name": "Saudi Pro League",
      "country": "Saudi Arabia",
      "base": 1.58,
      "tier": 2,
      "noise": 0.09,
      "teams": [
        ["Al-Hilal", "HIL", 1.86, 0.8],
        ["Al-Nassr", "NAS", 1.7, 0.88],
        ["Al-Ittihad", "ITT", 1.56, 0.94],
        ["Al-Ahli", "AHL", 1.5, 0.92],
        ["Al-Qadsiah", "QAD", 1.24, 0.98],
        ["Al-Shabab", "SHB", 1.22, 1.04],
        ["Al-Ettifaq", "ETT", 1.1, 1.06],
        ["Al-Taawoun", "TAA", 1.06, 1.04],
        ["Al-Fateh", "FAT", 1, 1.1],
        ["Al-Raed", "RAE", 0.94, 1.12],
        ["Damac", "DAM", 0.92, 1.1],
        ["Al-Khaleej", "KHA", 0.98, 1.08],
        ["Al-Riyadh", "RIY", 0.9, 1.08],
        ["Al-Okhdood", "OKH", 0.86, 1.12],
        ["Al-Fayha", "FAY", 0.88, 1.1],
        ["Al-Hazem", "HAZ", 0.84, 1.14],
        ["Neom SC", "NEO", 1.08, 1.06],
        ["Al-Najma", "NAJ", 0.8, 1.14],
      ],
    },
    {
      "code": "MLS",
      "name": "Major League Soccer",
      "country": "USA",
      "base": 1.62,
      "tier": 2,
      "noise": 0.08,
      "teams": [
        ["Inter Miami", "MIA", 1.72, 1.06],
        ["LAFC", "LAFC", 1.52, 0.98],
        ["Columbus Crew", "CLB", 1.46, 0.96],
        ["Atlanta United", "ATL", 1.2, 1.14],
        ["Seattle Sounders", "SEA", 1.3, 0.98],
        ["Philadelphia Union", "PHI", 1.28, 0.94],
        ["Cincinnati", "CIN", 1.34, 1.06],
        ["Orlando City", "ORL", 1.26, 1.04],
        ["NYCFC", "NYC", 1.22, 1.02],
        ["Charlotte FC", "CHA", 1.16, 1],
        ["Nashville SC", "NSH", 1.18, 0.98],
        ["Austin FC", "ATX", 1.1, 1.06],
        ["Portland Timbers", "POR", 1.12, 1.16],
        ["LA Galaxy", "LAG", 1.24, 1.2],
        ["Real Salt Lake", "RSL", 1.08, 1.08],
        ["New England", "NE", 1.02, 1.16],
        ["Toronto FC", "TOR", 0.96, 1.18],
        ["DC United", "DC", 0.98, 1.14],
        ["Minnesota United", "MIN", 1.14, 1.06],
        ["Vancouver Whitecaps", "VAN", 1.26, 1],
      ],
    },
    {
      "code": "EFLC",
      "name": "EFL Championship",
      "country": "England",
      "base": 1.34,
      "tier": 2,
      "noise": 0.07,
      "teams": [
        ["Leicester City", "LEI", 1.42, 0.92],
        ["Ipswich Town", "IPS", 1.36, 0.94],
        ["Southampton", "SOU", 1.32, 0.96],
        ["Middlesbrough", "MID", 1.24, 0.98],
        ["Coventry City", "COV", 1.26, 1],
        ["Watford", "WAT", 1.18, 1],
        ["Bristol City", "BRC", 1.12, 1],
        ["West Brom", "WBA", 1.14, 0.96],
        ["Norwich City", "NOR", 1.2, 1.1],
        ["Hull City", "HUL", 1.1, 1.04],
        ["Millwall", "MIL", 1.02, 0.98],
        ["Swansea City", "SWA", 1.04, 1.04],
        ["Stoke City", "STO", 1, 1.04],
        ["Preston NE", "PNE", 0.98, 1.02],
        ["QPR", "QPR", 1.02, 1.08],
        ["Sheffield Wednesday", "SHW", 0.92, 1.08],
        ["Blackburn", "BBR", 1.04, 1.1],
        ["Derby County", "DER", 0.94, 1.04],
        ["Portsmouth", "POR", 0.96, 1.06],
        ["Birmingham City", "BIR", 1.16, 1],
        ["Wrexham", "WRE", 1.08, 1.06],
        ["Oxford United", "OXF", 0.9, 1.06],
        ["Charlton", "CHA", 0.96, 1.02],
        ["Sheffield United", "SHU", 1.22, 0.98],
      ],
    },
  ],
  "basketball": [
    {
      "code": "NBA",
      "name": "NBA",
      "country": "USA",
      "base": 114,
      "sigma": 11.6,
      "tier": 1,
      "noise": 0.045,
      "teams": [
        ["Oklahoma City Thunder", "OKC", 9.4],
        ["Boston Celtics", "BOS", 6.6],
        ["Denver Nuggets", "DEN", 5.8],
        ["New York Knicks", "NYK", 5.2],
        ["Cleveland Cavaliers", "CLE", 5.6],
        ["Milwaukee Bucks", "MIL", 2.6],
        ["Minnesota Timberwolves", "MIN", 4.8],
        ["Houston Rockets", "HOU", 4.4],
        ["LA Clippers", "LAC", 2.2],
        ["Dallas Mavericks", "DAL", 2.4],
        ["Phoenix Suns", "PHX", 1.8],
        ["Golden State Warriors", "GSW", 1.6],
        ["Orlando Magic", "ORL", 3.2],
        ["Indiana Pacers", "IND", 2.8],
        ["Memphis Grizzlies", "MEM", 2],
        ["Sacramento Kings", "SAC", -0.6],
        ["Los Angeles Lakers", "LAL", 1.2],
        ["Atlanta Hawks", "ATL", 0.6],
        ["Detroit Pistons", "DET", 3.4],
        ["Miami Heat", "MIA", 0.4],
        ["Philadelphia 76ers", "PHI", 0.8],
        ["San Antonio Spurs", "SAS", 2.6],
        ["Toronto Raptors", "TOR", -1.6],
        ["Portland Trail Blazers", "POR", -4.2],
        ["New Orleans Pelicans", "NOP", -3.4],
        ["Utah Jazz", "UTA", -5.2],
        ["Charlotte Hornets", "CHA", -5],
        ["Chicago Bulls", "CHI", -2.4],
        ["Brooklyn Nets", "BKN", -6.2],
        ["Washington Wizards", "WAS", -7.4],
      ],
    },
    {
      "code": "EURO",
      "name": "EuroLeague",
      "country": "Europe",
      "base": 82,
      "sigma": 9.6,
      "tier": 2,
      "noise": 0.07,
      "teams": [
        ["Real Madrid", "RMB", 6.4],
        ["Panathinaikos", "PAO", 6],
        ["Fenerbahçe", "FEN", 5.6],
        ["Olympiacos", "OLY", 5.4],
        ["Barcelona", "FCB", 4.2],
        ["Monaco", "MON", 4],
        ["Anadolu Efes", "EFE", 2.2],
        ["Maccabi Tel Aviv", "MAC", 1.6],
        ["Olimpia Milano", "MIL", 1.2],
        ["Bayern München", "BAY", 0.8],
        ["Partizan", "PAR", 2],
        ["Crvena zvezda", "CZV", 1.8],
        ["Baskonia", "BAS", 1],
        ["Žalgiris", "ZAL", 2.4],
        ["Paris Basketball", "PARIS", 3.6],
        ["Virtus Bologna", "VIR", 0.4],
        ["Valencia Basket", "VAL", 0.6],
        ["ASVEL", "ASV", -3.2],
        ["Alba Berlin", "ALB", -4],
        ["Dubai Basketball", "DUB", -1],
      ],
    },
    {
      "code": "BAL",
      "name": "Basketball Africa League",
      "country": "Africa",
      "base": 74,
      "sigma": 10.4,
      "tier": 3,
      "noise": 0.11,
      "teams": [
        ["Al Ahly Ly", "AHL", 6.2],
        ["Petro de Luanda", "PET", 5.8],
        ["US Monastir", "USM", 4.6],
        ["Rivers Hoopers", "RIV", 3.4],
        ["AS Douanes", "DOU", 2.6],
        ["APR BBC", "APR", 2.2],
        ["Stade Malien", "STM", 1.8],
        ["FAP Yaoundé", "FAP", 0.6],
        ["Cape Town Tigers", "CTT", 0.2],
        ["Feroviário", "FER", -0.8],
        ["Espoir Fukash", "ESP", -2.4],
        ["Al Ittihad Alexandria", "ITT", 3],
      ],
    },
  ],
  "baseball": [
    {
      "code": "MLB",
      "name": "MLB",
      "country": "USA",
      "base": 4.55,
      "sigma": 3.5,
      "tier": 1,
      "noise": 0.05,
      "teams": [
        ["LA Dodgers", "LAD", 1.35],
        ["NY Yankees", "NYY", 0.85],
        ["Philadelphia Phillies", "PHI", 0.8],
        ["Milwaukee Brewers", "MIL", 0.7],
        ["Atlanta Braves", "ATL", 0.55],
        ["Houston Astros", "HOU", 0.45],
        ["Baltimore Orioles", "BAL", 0.4],
        ["San Diego Padres", "SDP", 0.55],
        ["Arizona Diamondbacks", "AZD", 0.35],
        ["Kansas City Royals", "KCR", 0.3],
        ["Minnesota Twins", "MIN", 0.15],
        ["Detroit Tigers", "DET", 0.45],
        ["Cleveland Guardians", "CLE", 0.35],
        ["Seattle Mariners", "SEA", 0.4],
        ["Toronto Blue Jays", "TOR", 0.45],
        ["Boston Red Sox", "BOS", 0.35],
        ["Tampa Bay Rays", "TB", 0.15],
        ["Cincinnati Reds", "CIN", 0.1],
        ["St. Louis Cardinals", "STL", 0],
        ["NY Mets", "NYM", 0.35],
        ["Chicago Cubs", "CHC", 0.3],
        ["San Francisco Giants", "SFG", 0.1],
        ["Texas Rangers", "TEX", 0.05],
        ["Pittsburgh Pirates", "PIT", -0.1],
        ["Oakland Athletics", "OAK", -0.45],
        ["LA Angels", "LAA", -0.4],
        ["Washington Nationals", "WSH", -0.55],
        ["Miami Marlins", "MIA", -0.5],
        ["Colorado Rockies", "COL", -0.9],
        ["Chicago White Sox", "CWS", -0.6],
      ],
    },
  ],
  "tennis": {
    "code": "ATPWTA",
    "name": "Tour Events",
    "country": "International",
    "tier": 1,
    "noise": 0.055,
    "scale": 7.5,
    "players": [
      ["Jannik Sinner", 88],
      ["Carlos Alcaraz", 89],
      ["Novak Djokovic", 82],
      ["Alexander Zverev", 78],
      ["Daniil Medvedev", 72],
      ["Taylor Fritz", 70],
      ["Casper Ruud", 66],
      ["Alex de Minaur", 69],
      ["Andrey Rublev", 68],
      ["Holger Rune", 64],
      ["Hubert Hurkacz", 63],
      ["Stefanos Tsitsipas", 64],
      ["Tommy Paul", 66],
      ["Ben Shelton", 67],
      ["Lorenzo Musetti", 66],
      ["Jack Draper", 68],
      ["Frances Tiafoe", 60],
      ["Karen Khachanov", 61],
      ["Ugo Humbert", 60],
      ["Sebastian Korda", 60],
      ["Aryna Sabalenka", 88],
      ["Iga Świątek", 87],
      ["Coco Gauff", 82],
      ["Elena Rybakina", 79],
      ["Jasmine Paolini", 72],
      ["Jessica Pegula", 73],
      ["Qinwen Zheng", 74],
      ["Mirra Andreeva", 76],
      ["Madison Keys", 71],
      ["Barbora Krejčíková", 66],
      ["Emma Navarro", 66],
      ["Danielle Collins", 67],
      ["Karolína Muchová", 65],
      ["Daria Kasatkina", 62],
      ["Anna Kalinskaya", 61],
      ["Marta Kostyuk", 60],
    ],
  },
  "mma": {
    "code": "UFC",
    "name": "UFC",
    "country": "International",
    "tier": 1,
    "noise": 0.085,
    "scale": 6.5,
    "fighters": [
      ["Jon Jones", 90],
      ["Tom Aspinall", 86],
      ["Ciryl Gane", 78],
      ["Sergei Pavlovich", 76],
      ["Islam Makhachev", 89],
      ["Arman Tsarukyan", 81],
      ["Charles Oliveira", 76],
      ["Benoît Saint Denis", 72],
      ["Ilia Topuria", 88],
      ["Alexander Volkanovski", 82],
      ["Max Holloway", 80],
      ["Diego Lopes", 76],
      ["Merab Dvalishvili", 85],
      ["Sean O'Malley", 80],
      ["Petr Yan", 79],
      ["Umar Nurmagomedov", 80],
      ["Alexandre Pantoja", 81],
      ["Joshua Van", 76],
      ["Brandon Moreno", 78],
      ["Deiveson Figueiredo", 74],
      ["Alex Pereira", 84],
      ["Magomed Ankalaev", 85],
      ["Jiri Prochazka", 79],
      ["Jamahal Hill", 74],
      ["Dricus du Plessis", 82],
      ["Israel Adesanya", 76],
      ["Khamzat Chimaev", 88],
      ["Robert Whittaker", 76],
      ["Belal Muhammad", 81],
      ["Shavkat Rakhmonov", 84],
      ["Jack Della Maddalena", 80],
      ["Bo Nickal", 76],
      ["Anatoly Malykhin", 78],
      ["Ian Machado Garry", 77],
      ["Cory Sandhagen", 77],
      ["Aljamain Sterling", 76],
    ],
  },
};

export default RATINGS;
